### ISSUE TITLE
Behöver en plats för gamla kodprov

### ISSUE THREAD

**Issue by TobiasWrigstad** [IOOPM-UU/ioopm15#1]
Även om det inte är så vettigt att läsa dem så kommer de bli efterfrågade som vanligt.

**Comment by TobiasWrigstad** [comment]
Och… lägg en länk dit från länksidan på kurswebben.

**Comment by EliasC** [comment]
Fixat: Se [här](https://github.com/IOOPM-UU/ioopm15/tree/master/extramaterial/gamlakodprov).
