### ISSUE TITLE
[Question][sprint 1-2] frihet gällande databaslagring

### ISSUE THREAD

**Issue by phroggyy** [IOOPM-UU/ioopm15#11]
Hur fria är vi att bygga egna trädstrukturer för sprint 1 & 2? För någon van vid användande av "vanliga" databaser, känns det väldigt fel att skapa en struct som implementeras med fast storlek, måste man göra detta eller kan man direkt lösa det som det ska göras i 2. Även i sprint 2, där det är ett binärt sökträd undrar jag om man istället kan använda ett mer generellt B-träd för att kunna använda bl. a indexering?

(Skulle helst självklart använda t ex SQLite, men då man då inte bygger upp trädet själv antar jag att det inte tillåts)

**Comment by EliasC** [comment]
> Hur fria är vi att bygga egna trädstrukturer för sprint 1 & 2? För någon van vid användande av "vanliga" databaser, känns det väldigt fel att skapa en struct som implementeras med fast storlek, måste man göra detta eller kan man direkt lösa det som det ska göras i 2. Även i sprint 2, där det är ett binärt sökträd undrar jag om man istället kan använda ett mer generellt B-träd för att kunna använda bl. a indexering?

Jag skulle säga att detta räknas som en "frivillig utökning", vilket alltså är okej (även i den första sprinten). Anledningen till att vi börjar med en enklare implementation är förstås för att många inte har programmerat C alls tidigare, och vi vill att alla ska kunna hänga med!

> (Skulle helst självklart använda t ex SQLite, men då man då inte bygger upp trädet själv antar jag att det inte tillåts)

Det blir svårt att visa att man kan hantera pekare, länkade strukturer, minneshantering och så vidare om man inte implementerar datastrukturerna själv, och i slutändan är det ett viktigare mål i den här kursen än att lära sig hantera existerande implementationer.

**Comment by EliasC** [comment]
Metakommentar: Frågor som den här, som rör kursens uppgifter och hur de bedöms, får du gärna ställa på Piazza istället där fler har möjlighet att läsa svaren (men fortsätt gärna kommentera materialet på GitHub också!).

**Comment by TobiasWrigstad** [comment]
Notera att du så småningom skall byta kod etc. med andra och att det finns interface som skall efterföljas. Bara så att du inte stöter på patrull för att ingen annan vill/kan byta kod med dig. Etc. I övrigt, vad Elias sade!

**Comment by phroggyy** [comment]
Tack @EliasC och @TobiasWrigstad för svaren! Och absolut ska jag se till att skriva förståelig kod och abstrahera ut så mycket komplexitet som möjligt för att bara hålla högnivåfunktioner i den faktiska koden, så får man grotta ned sig gradvis. :blush:
