### ISSUE TITLE
Instruktionerna för att hämta .el-filerna är *fel*

### ISSUE THREAD

**Issue by amandasystems** [IOOPM-UU/ioopm15#16]
...och leder till att man får HTML-filer istället. De måste gå till raw-filerna, så här: https://raw.githubusercontent.com/IOOPM-UU/ioopm15/master/extramaterial/emacs/ioopm.el

**Comment by TobiasWrigstad** [comment]
Var finns dessa instruktioner som är fel?

**Comment by amandasystems** [comment]
I readme.md

**Comment by TobiasWrigstad** [comment]
Tack. Finns sjukt många README.md — men jag listade ut vilken du menade. Jag är trött i huvudet idag.
