### ISSUE TITLE
Fel i kom igång-uppgiften i Java

### ISSUE THREAD

**Issue by mb3331** [IOOPM-UU/ioopm15#17]
I readmen för kom igång-uppgiften i Java under "Fortsätt själv" (https://github.com/IOOPM-UU/ioopm15/tree/master/uppgifter/fas2/sprint1/komigang#forts%C3%A4tt-sj%C3%A4lv), steg 2, står det att man ska ändra koden 

Die die = new Die();
System.out.println(die.get());

i Die.java. Men den finns ingenstans i koden vad jag kan se.

**Comment by tobiasholmberg** [comment]
Som jag förstår texten så ska du ska skriva ett program som kör de raderna efter att du förstått vad som blir fel för att få "facit". Sen ska du ändra i Die.java så att koden nämner blir meningsfull.

**Comment by mb3331** [comment]
Ja, men jag hittar inte dem två raderna i Die.java, så jag vet inte vad jag ska ändra. Eller är det meningen att man ska lägga till dem?

**Comment by tobiasholmberg** [comment]
Du ska skriva de raderna i en main-metod, de kommer inte fungera som förväntat. Som jag förstår det så ska du sen rätta till Die klassen så att de raderna fungerar som förväntat.

**Comment by mb3331** [comment]
Ah ok, tack för svaret. Jag ska testa det :)

**Comment by EliasC** [comment]
@mb3331: @tobiasholmberg har helt rätt. Du ska skriva in de två raderna själv, och sen ändra i Die-klassen så att du får ett vettigt resultat. Men du gjorde helt rätt som öppnade en issue i frågan!
